version: "3.2"

services:
  direct-debit-submission:
    image: direct-debit-submission
    build:
      context: .
      dockerfile: DirectDebitSubmission/Dockerfile
      args:
        - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
    ports:
      - 3000:3000
    environment:
     - ENVIRONMENT=LocalDevelopment
      # Alter if not using DynamoDb
     - DynamoDb_LocalMode=true
     - DynamoDb_LocalServiceUrl=http://dynamodb-database:8000
     - AWS_REGION=eu-west-2
     - AWS_ACCESS_KEY_ID=local
     - AWS_SECRET_ACCESS_KEY=local

  direct-debit-submission-test:
    image: direct-debit-submission-test
    build:
      context: .
      dockerfile: DirectDebitSubmission.Tests/Dockerfile
      args:
        - LBHPACKAGESTOKEN=${LBHPACKAGESTOKEN}
        - SONAR_TOKEN=${SONAR_TOKEN}
    environment:
      - ENVIRONMENT=LocalDevelopment
      # Alter if not using DynamoDb
      - DynamoDb_LocalMode=true
      - DynamoDb_LocalServiceUrl=http://dynamodb-database:8000
      - AWS_REGION=eu-west-2
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local